import { createCanvas } from "canvas";
import fs from "fs/promises";

/**
 * createSummaryImage({ total, top5, timestamp, outPath })
 * - total: integer
 * - top5: array of Sequelize model instances (Country)
 * - timestamp: Date
 * - outPath: destination PNG path
 */
export async function createSummaryImage({ total, top5, timestamp, outPath }) {
  const width = 1200;
  const height = 628;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");

  // Background
  ctx.fillStyle = "#0f172a";
  ctx.fillRect(0, 0, width, height);

  // Title
  ctx.fillStyle = "#fff";
  ctx.font = "bold 36px Sans";
  ctx.fillText("Countries Cache Summary", 40, 60);

  ctx.font = "22px Sans";
  ctx.fillStyle = "#d1d5db";
  ctx.fillText(`Total countries: ${total}`, 40, 110);
  ctx.fillText(`Last refresh: ${timestamp.toISOString()}`, 40, 140);

  // Top 5 list
  ctx.font = "20px Sans";
  ctx.fillStyle = "#fff";
  ctx.fillText("Top 5 by estimated GDP:", 40, 190);

  ctx.font = "18px Sans";
  let y = 230;
  for (let i = 0; i < top5.length; i++) {
    const c = top5[i];
    const gdpDisplay =
      c.estimated_gdp === null || c.estimated_gdp === undefined
        ? "N/A"
        : Number(c.estimated_gdp).toLocaleString(undefined, {
            maximumFractionDigits: 0,
          });
    ctx.fillText(`${i + 1}. ${c.name} — ${gdpDisplay}`, 60, y);
    y += 34;
  }

  // Footer small note
  ctx.font = "14px Sans";
  ctx.fillStyle = "#9ca3af";
  ctx.fillText("Generated by Country Currency & Exchange API", 40, height - 40);

  const buffer = canvas.toBuffer("image/png");
  await fs.writeFile(outPath, buffer);
}